from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("MyTestApp").master("local[1]").getOrCreate()
spark.sparkContext.setLogLevel("ERROR")
customers = spark.read.csv("Demo/customers.csv", header=True, inferSchema=True)
customers.show(2)
customers.printSchema()
df = customers.select("customer_id", "customer_name", "city", "customer_segment")
df.show(2)
filtered_df = df.filter(df.city == "New York")
filtered_df.show(2)
city_df = customers.groupBy("city").count()
city_df.show()
segment_df = customers.filter(customers.customer_segment == "Small Business")
print(segment_df.count())
